-- Fase 0 - baseline estrutural PostgreSQL para configuracao futura e refresh token.
-- Caminho oficial: revisar este script junto do modelo EF Core antes de aplicar em ambiente real.
-- Nao aplica regra de negocio nova; apenas prepara tabelas de fundacao.

CREATE TABLE IF NOT EXISTS configuracoes_grupo (
    id_configuracao_grupo numeric(20, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_grupo numeric(20, 0) NOT NULL,
    tipo_jogo varchar(30) NOT NULL DEFAULT 'FUTEBOL',
    formato_jogo varchar(30) NOT NULL DEFAULT 'DOIS_TIMES',
    quantidade_times integer NOT NULL DEFAULT 2,
    pontos_vitoria integer NOT NULL DEFAULT 4,
    pontos_derrota integer NOT NULL DEFAULT 1,
    pontos_empate integer NOT NULL DEFAULT 0,
    pontos_presenca integer NOT NULL DEFAULT 0,
    maximo_goleiros_por_partida integer NOT NULL DEFAULT 2,
    criado_em timestamp with time zone NOT NULL DEFAULT now(),
    atualizado_em timestamp with time zone NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_configuracoes_grupo_id_grupo
    ON configuracoes_grupo (id_grupo);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id_refresh_token numeric(20, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario numeric(20, 0) NOT NULL,
    token_hash varchar(128) NOT NULL,
    expira_em timestamp with time zone NOT NULL,
    revogado_em timestamp with time zone NULL,
    criado_por_ip varchar(80) NULL,
    revogado_por_ip varchar(80) NULL,
    criado_em timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_refresh_tokens_token_hash
    ON refresh_tokens (token_hash);

CREATE INDEX IF NOT EXISTS ix_refresh_tokens_id_usuario_criado_em
    ON refresh_tokens (id_usuario, criado_em);
